name = "Glorier"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a08bcdda960589bda7adcab0c3aff66db8bfa11aace09992a9a97f7ec511813"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
