name = "Glorier"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe9bccae70d27317d6af3406cedc2d797f0feaa20ed8d522300d36a74105f325"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
