name = "Glorier"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "038fdedb98e128ce6f774c575b10a845a27700db68c2e8b66721ed6b0b582942"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
