name = "Glorier"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "974ceaa84ad6d6424d2fc012a9f283400b2495c458120d582d4e104cf7ecbbb5"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
