name = "Glorier"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "247518ab811b9ced506e8c9057f373f885f2b7e217766ea5cdadab49fc58a750"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
